### ISSUE TITLE
Unable to start if there's Azure storage transient connection issue during startup with CreateIfNotExists=true

### ISSUE THREAD

**Issue by euyuil** [jviau/durabletask-hosting#17]
Repro steps:

1. Set `TaskHubOptions.CreateIfNotExists` to `true` (which is the default setting).
2. Disconnect from the Internet.
3. Run the program.

A `Microsoft.WindowsAzure.Storage.StorageException` will be thrown from:

https://github.com/jviau/durabletask-hosting/blob/7da08e511462d3cd29ca377ce5d87bb72c7238c1/src/DurableTask.Hosting/src/TaskHubBackgroundService.cs#L49

If `TaskHubOptions.CreateIfNotExists` is set to `false`, and the resources have already been created, the host can start without uncaught exceptions even if disconnected from the Internet. Once the Internet connection is back, the worker will work correctly.

I'm wondering if my proposal is acceptable: Some error handling (catch-retry) can be added to that line, so the `TaskHubBackgroundService` can start with Azure storage transient connection errors, when `TaskHubOptions.CreateIfNotExists` is set to `true`. The resources are expected to be `Create`ed`IfNotExists` when the Internet connection is back.

**Comment by jviau** [comment]
Can you elaborate on your use case for wanting this to work without internet? From my view it is a bit unnecessary, even if the host starts up there is nothing for it to do without internet. Additionally, this would be tricky to implement as each `IOrchestrationService` may have different behavior when there is no internet, and it could change overtime as they update their internal workings.

**Comment by jviau** [comment]
Revisiting this: I think this functionality is best left outside of this library for a couple reasons:

1. This can be solved without the change.
    - You can set `CreateIfNotExists` to `false` and instead import `TaskHubWorker` after building your host, but before starting it, and perform the try/catch logic there.
    - You can let it fail and have your hosting service of choice perform the restart of the process. I believe k8s can do this.
2. This is similar to many other transient startup issues that are not retried. AspNetCore failing to bind to the selected port, `IConfigurationSource` failing to connect to its backing source, etc.

Closing unless I see compelling reason this must be included in the library and cannot be done outside of it.
