### ISSUE TITLE
Unable to run service bus sample

### ISSUE THREAD

**Issue by cecilphillip** [jviau/durabletask-hosting#31]
I uncommented the code for azure service bus, but I was unable to get it to run. I kept crashing with a "Bad Request" error message.  What do I need to get this to run with service bus?

(Awesome library btw... it would be nice to have some of the primitives in the DurableTask.Core)

**Comment by jviau** [comment]
@cecilphillip did you set up the connection string for service bus in `appsettings.json`? Or user secrets?

Also, service bus orchestrator is not in active development, I would recommend using Azure Storage orchestrator instead. I'll update the sample for that when I have time.

**Comment by cecilphillip** [comment]
That's what everyone says about the service bus supports lol. I guess I'll just leave it alone for now.
