### ISSUE TITLE
Would that work with WebApplicationBuilder from net70 Minimal APIs?

### ISSUE THREAD

**Issue by christophwille** [jviau/durabletask-hosting#52]
Just tried to do that, but 

```
var builder = WebApplication.CreateBuilder(args);
builder.ConfigureTaskHubWorker()
```

won't work (rather unsurprisingly). What workaround would you suggest? (given that the "root" ConfigureTaskHubWorker only really interacts with IServiceCollection)

**Comment by jviau** [comment]
I think `builder.Host.ConfigureTaskHubWorker()` should work.

**Comment by christophwille** [comment]
![image](https://github.com/jviau/durabletask-hosting/assets/344208/76c400fa-4f67-425f-974f-cca74caa576c)


The Host essentially is an IHostBuilder.

**Comment by jviau** [comment]
`IHostBuilder` is what is expected: https://github.com/jviau/durabletask-hosting/blob/main/src/DurableTask.Hosting/src/Extensions/TaskHubHostBuilderExtensions.cs#L22

Are you missing a `using` statement?

**Comment by christophwille** [comment]
Ah, I had the DI package installed, not the Hosting one.
