### ISSUE TITLE
Inject Logger into taskhub worker and client

### ISSUE THREAD

**Issue by gauravvgat** [jviau/durabletask-hosting#53]
I'm trying to create taskhub worker as part of aspnet core program.cs. How do I inject logger into taskhubworker and client?
builder.Host.ConfigureTaskHubWorker((context, builder) =>
            {
                builder.WithOrchestrationService(provider);
                builder.AddActivity<TAct1>();
                builder.AddActivity<TAct2>();
                builder.AddOrchestration<TOrch>();
                builder.AddClient();                
            });

I tried calling 
builder.Logging.AddConsole(); above the ConfigureTaskHubWorker but it's not resolving.

**Comment by jviau** [comment]
`ILoggerFactory` is resolved from `IServiceProvider` and supplied to both `TaskHubWorker` and `TaskHubClient`, so there is nothing you need to do.

> builder.Logging.AddConsole(); above the ConfigureTaskHubWorker but it's not resolving.

Can you clarify what you mean by "it's not resolving"? What exactly isn't resolving?

https://github.com/jviau/durabletask-hosting/blob/5d2328d295c3030f1870fdef10328270fcba502a/src/DurableTask.DependencyInjection/src/DefaultTaskHubWorkerBuilder.cs#L81-L86

https://github.com/jviau/durabletask-hosting/blob/5d2328d295c3030f1870fdef10328270fcba502a/src/DurableTask.DependencyInjection/src/Extensions/TaskHubWorkerBuilderExtensions.cs#L84-L85

**Comment by jviau** [comment]
No response for a bit - closing. Please re-open if you are still seeing this issue.

**Comment by jviau** [comment]
#stale
