### ISSUE TITLE
DI Guidance Needed

### ISSUE THREAD

**Issue by zpertee** [jviau/durabletask-hosting#59]
I'm sorry for what I'm sure is an ignorant question, but any chance you can help clarify what the proper approach for me to get the singleton instance of MyOrchestratorInfo from the ServiceCollection to satisfy my ConfigureTaskHubWorker?  Seems like what I did below is likely not proper, but I'm uncertain how to fix.  

```
pWebApplicationBuilder.Host.ConfigureTaskHubWorker((context, taskhub_builder) =>
{
	MyOrchestratorInfo lMyOrchestratorInfo = null;
	using (var lTempSP = taskhub_builder.Services.BuildServiceProvider())
	{
		lMyOrchestratorInfo = lTempSP.GetService<MyOrchestratorInfo>();
	}

	// add orchestration service
	taskhub_builder.WithOrchestrationService(lMyOrchestratorInfo.GetOrchestrationService());

	//Get List of Orchestrations & Activities 
	List<Type> lOrchestrators = GetOrchestratorTypes();
	List<Type> lTaskActivities = GetTaskActivityTypes();

	//Add Orchestrators
	lOrchestrators.ForEach(lSelectedType => taskhub_builder.AddOrchestration(lSelectedType));

	//Add Activities
	lTaskActivities.ForEach(lSelectedType => taskhub_builder.AddActivity(lSelectedType));
});
```

**Comment by jviau** [comment]
@zpertee you do not need to retrieve your orchestrator at all. All you need to do is register your orchestrations in `ConfigureTaskHubWorker` via type, not instance. You can then _optionally_ register your orchestrations or activities to the `IServiceCollection`. Registering to IServiceCollection is only when you want to explicitly control construction or lifetime. If you do not register, then it is still DI'd, with a transient lifetime.

``` CSharp
.ConfigureServices(services =>
{
    services.AddSingleton<MyOrchestrationInstance>(); // This is optional. Not registering will mean a transient lifetime.
})
.ConfigureTaskHubWorker((context, builder) =>
{
    builder.AddOrchestration<MyOrchestrationInstance>(); // this will be DI'd, regardless of if it was explicitly registered to IServiceCollection or not.
});
```

**Comment by zpertee** [comment]
Thank you!  I was struggling to look at this from the right angle and you got me on the right track now.  :)
